### ISSUE TITLE
ERROR Error: Cannot find module "./pt-BR.js"

### ISSUE THREAD

**Issue by vdurante** [aspnetboilerplate/module-zero-core-template#368]
Looking at the commits, I noticed a few changes were made regarding how angular deals with i18n. I didn't really understand why that was made, but after I upgraded my application to 4.2.1, the application when debugging, but doesn't work on release. I am getting error `ERROR Error: Cannot find module "./pt-BR.js"`. Any ideas on why?

**Comment by ismcagdas** [comment]
@vdurante I think you have figured it out 😄. Here is the related issue https://github.com/aspnetboilerplate/module-zero-core-template/issues/315
